routes/web.php
<?php

/*DB::listen(function($query)
{
	echo "<pre>{{$query->sql}}</pre>";  // Para ver las consultas sql que se estan generando.
});*/


Route::group([
	'prefix'	=> 'panel'
], function() {

	// Authentication Routes...
	Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
	Route::post('/', 'Admin\Auth\LoginController@login');
	Route::post('logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

	// Password Reset Routes...
	Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

	Route::get('home', 'Admin\HomeController@index')->name('admin.home');


	// Categorias
	Route::resource('categorias', 'Admin\CategoryController', [
		'names' => 'admin.categorias'
	]);
	Route::post('categorias/orden', 'Admin\CategoryController@sort');
	Route::post('categorias/categoriasUpload', 'Admin\CategoryController@upload')->name('admin.categories.upload.store');
	Route::post('categorias/deleteCategoriesImage', 'Admin\CategoryController@destroyImage')->name('admin.categories.upload.destroy');


	// Usuarios
	Route::resource('users', 'Admin\UserController', [
		'names' 	=> 'admin.users',
		'except'	=> 'show'
	]);

	// Marcas
	Route::resource('marcas', 'Admin\BrandController', [
		'names' 	=> 'admin.brands',
		'except'	=> 'show'
	]);

	// Attributes
	Route::resource('attributes', 'Admin\AttributeController', [
		'names' 	=> 'admin.attributes',
		'except'	=> 'show'
	]);


	// Attribute Groups
	Route::resource('groups', 'Admin\GroupController', [
		'names' 	=> 'admin.groups',
		'except'	=> 'show'
	]);

	// Features
	Route::resource('features', 'Admin\FeatureController', [
		'names' 	=> 'admin.features',
		'except'	=> 'show'
	]);

	Route::post('features/featuresUpload', 'Admin\FeatureController@upload')->name('admin.features.upload.store');
	Route::post('features/deleteFeaturesImage', 'Admin\FeatureController@destroyImage')->name('admin.features.upload.delete');


	// Productos
	Route::get('productos/importar', 'Admin\ProductController@importForm');
	Route::post('productos/importar', 'Admin\ProductController@import');
	Route::get('productos/modelo', 'Admin\ProductController@downloadImportModel');
	Route::get('productos/guia', 'Admin\ProductController@downloadImportGuide');
	Route::resource('productos', 'Admin\ProductController', [
		'names' => 'admin.productos'
	]);

	Route::post('productos/{product}/destroyManual', 'Admin\ProductController@destroyManual');


	// Productos Media
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('atributos', 'Admin\ProductController@atributos')->name('admin.productos.atributos');

		Route::post('atributos/delete', 'Admin\ProductController@deleteAtributo')->name('admin.productos.atributos.delete');

		Route::post('atributos/add', 'Admin\ProductController@addAtributos')->name('admin.productos.atributos.agregar');

		Route::get('{product}/files/create', 'Admin\ProductMediaController@create')->name('admin.productos.files.create');
		
		Route::post('{product}/files', 'Admin\ProductMediaController@store')->name('admin.productos.files.store');
		
		Route::post('{product}/files/ordenar', 'Admin\ProductMediaController@ordenar')->name('admin.productos.section.ordenar');

		Route::delete('{product}/files/{id}', 'Admin\ProductMediaController@destroy')->name('admin.productos.files.destroy');

		Route::post('{product}/deleteFilesImage', 'Admin\ProductMediaController@destroyImage')->name('admin.productos.files.destroy.images');

	});

	// Productos modulo seccion
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('{product}/section', 'Admin\ProductSectionController@store')->name('admin.productos.section.store');
		

		Route::delete('{product}/section/{id}', 'Admin\ProductSectionController@destroy')->name('admin.productos.section.destroy');
		

		Route::post('{product}/sectionUpload', 'Admin\ProductSectionController@upload')->name('admin.productos.section.upload');

		Route::post('{product}/deleteProductSectionImage', 'Admin\ProductSectionController@destroyImage')->name('admin.productos.section.destroyImage');
		
	});

	// Widgets
	Route::delete('widgets/media/{id}', 'Admin\WidgetController@deleteMedia')->name('admin.widgets.media.delete');

	Route::post('widgets/media', 'Admin\WidgetController@createMedia')->name('admin.widgets.media.store');

	Route::resource('widgets', 'Admin\WidgetController', [
		'names' => 'admin.widgets'
	]);

	Route::post('widgets/orden', 'Admin\WidgetController@ordenar')->name('admin.widgets.media.orden');

	Route::resource('slider', 'Admin\SliderController', [
		'names' => 'admin.slider'
	]);	

	Route::get('newsletter', 'NewsletterController@index')->name('admin.newsletter.index');

	// Novedades
	Route::resource('stories', 'Admin\StoryController', [
		'names' 	=> 'admin.stories',
		'except'	=> 'show'
	]);

	Route::post('stories/storiesUpload', 'Admin\StoryController@upload')->name('admin.stories.upload.store');

	// Categorias de novedades
	Route::resource('themes', 'Admin\ThemeController', [
		'names' 	=> 'admin.themes',
		'except'	=> 'show'
	]);

	// Tags
	Route::resource('tags', 'Admin\TagController', [
		'names' 	=> 'admin.tags',
		'except'	=> 'show'
	]);

	// Paginas
	Route::resource('pages', 'Admin\PageController', [
		'names' 	=> 'admin.pages',
		'except'	=> 'show'
	]);	
	Route::post('pages/orden', 'Admin\PageController@sort');
	Route::post('pages/upload', 'Admin\PageController@upload');

	//Contacto
	Route::get('contactos', 'Admin\ContactoController@index')->name('admin.contactos.index');

	//Customers
	Route::get('customers', 'Admin\CustomerController@index')->name('admin.customers.index');

	//Asuntos
	Route::resource('subjects', 'Admin\SubjectController', [
		'names' 	=> 'admin.subjects',
		'except'	=> 'show'
	]);

});


/********** FRONTEND **********/

Route::get('/', 'Front\HomeController@index')->name('home');

//Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!panel$).*$')->name('categoria');


Route::post('/newsletter', 'NewsletterController@store')->name('newsletter.store');


/*Route::get('/{category}/{subcategory?}/{product}', 'Front\ProductController@index')->name('productos');
Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto|descargas$).*$')->name('categoria');*/


// Authentication Routes...
Route::get('/login', 'Front\Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Front\Auth\LoginController@login');
Route::post('logout', 'Front\Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Front\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Front\Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Front\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Front\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Front\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Front\Auth\ResetPasswordController@reset');

// Perfil
Route::get('/perfil', 'Front\PerfilController@edit')->name('perfil.edit');
Route::put('/perfil', 'Front\PerfilController@update')->name('perfil.update');


// Contacto
Route::get('/contacto', 'Front\ContactoController@index')->name('contacto');
Route::post('/contacto', 'Front\ContactoController@store')->name('contacto.store');

// Descargas
Route::get('/descargas', 'Front\DescargasController@index')->name('descargas.index');

//Comparador
Route::post('/comparador/handle', 'Front\ComparadorController@handle');
Route::get('/comparador', 'Front\ComparadorController@index');

// Busquedas
Route::get('/busqueda', 'Front\BusquedaController@index')->name('busqueda.index');
Route::get('/autocomplete', 'Front\BusquedaController@autocomplete')->name('autocomplete');

Route::get('/{subcategory}/{product}', 'Front\ProductController@index')->name('productos');

Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto$).*$')->name('categoria');

app/User.php
<?php

namespace Noblex;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Noblex\Category;
use Noblex\Notifications\ResetPasswordNotification;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'gender', 'birth', 'admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace Noblex\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Noblex\Http\Controllers\Controller;
use Noblex\Repositories\Interfaces\UserInterface;

class UserController extends Controller
{
    private $user;

    public function __construct(UserInterface $user)
    {
        $this->middleware('auth');
        $this->user = $user;
    }


    public function index()
    {
        if (!\Auth::user()->admin) {
            return redirect('/panel');
        }

        $users = $this->user->getAll();

        return view('admin.pages.users.index', compact("users")); 
    }


    public function create()
    {
        return view('admin.pages.users.create');
    }


    public function store(Request $request)
    {
        $this->user->store($request);

        return redirect()->route('admin.users.index')->with('success', 'Usuario agregado correctamente.');
    }


    public function edit($id)
    {
        $user = $this->user->findById($id);
        $user->permissions = [];//'home', 'config'];
        return view('admin.pages.users.edit', compact("user"));
    }


    public function update(Request $request, $id)
    {
        $this->user->update($request, $id);

        return redirect()->route('admin.users.index')->with('info', 'Usuario editado correctamente.');
    }


    public function destroy($id)
    {
        $this->user->destroy($id);

        return redirect()->route('admin.users.index')->with('danger', 'Usuario eliminado correctamente.');
    }
}

resources/views/admin/pages/users/create.blade.php
@extends('admin.layouts.app')

@section('content')
	
	<div class="tab-pane">
		<div class="portlet box blue">

			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-plus"></i> Agregar usuario
				</div>
			</div>

			<div class="portlet-body form">

				<!-- BEGIN FORM-->
				{!! Form::open(['route' => 'admin.users.store', 'class' => 'form-horizontal form-row-seperated']) !!}

					@include('admin.pages.users.partials.form')
					
				{!! Form::close() !!}
				<!-- END FORM-->
				
			</div>
		</div>
	</div>

@endsection

resources/views/admin/pages/users/delete.blade.php
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Eliminar Usuario</h4>
      </div>

      <div class="modal-body">

        Desea eliminar el usuario: <strong><span id="nombre"></span></strong> ?
        
      </div>

      <div class="modal-footer">
        <form action="" method="POST" id="form-delete">

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

            @csrf
            {{ method_field('DELETE') }}

            <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Eliminar</button>

        </form>

      </div>
    </div>
  </div>
</div>

resources/views/admin/pages/users/edit.blade.php
@extends('admin.layouts.app')

@section('content')
	
	<div class="tab-pane">
		<div class="portlet box yellow">

			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-plus"></i> Editar usuario
				</div>
			</div>

			<div class="portlet-body form">
			
				<!-- BEGIN FORM-->
				{!! Form::model($user, ['route' => ['admin.users.update', $user->id], 'class' => 'form-horizontal form-row-seperated', 'method' => 'PUT']) !!}

					@include('admin.pages.users.partials.form')

					
				{!! Form::close() !!}
				<!-- END FORM-->
				
			</div>
		</div>
	</div>

@endsection

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.app')
	
@section('content')

	<div class="table-toolbar">
        <div class="row">
            <div class="col-md-6">
                <div class="btn-group">
                    <a href="{{ route('admin.users.create') }}" id="sample_editable_1_new" class="btn sbold green"> Agregar
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

	<div class="row">
		<div class="col-md-12">

			<table id="users" width="100%" class="table table-striped table-bordered table-hover">
				
				<thead>
					<tr>
						<th>Nombre</th>
						<th width="200">Opciones</th>
					</tr>
				</thead>

				<tbody>
					
					@foreach($users as $user)

					<tr>
						<td>{{ $user->name }}</td>
						<td>
							<div class="btn-group">
                    	        <a href="{{ route('admin.users.edit', $user->id) }}">
                                    <i class="icon-pencil"></i> Editar 
                                </a>
                                @if ($user->id != 1)
                                |
                                <a href="#" data-target='#modal-delete' data-toggle='modal' id="modal" 
                                	data-id="{{ $user->id }}"
                                	data-name="{{ $user->name }}"
                                	data-url="{{ route('admin.users.destroy', $user->id) }}">
                                    <i class="icon-trash"></i> Eliminar 
                                </a>
	                            @endif
                        	</div>
                    	</td>
					</tr>

					@endforeach

				</tbody>

			</table>

		</div>
	</div>
	
	@include('admin.pages.users.delete')

@endsection

@push('scripts')
    <script src="{{ asset('admin/assets/pages/marcas/js/main.js') }}"></script>
@endpush