routes/web.php
<?php

/*DB::listen(function($query)
{
	echo "<pre>{{$query->sql}}</pre>";  // Para ver las consultas sql que se estan generando.
});*/


Route::group([
	'prefix'	=> 'panel'
], function() {

	// Authentication Routes...
	Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
	Route::post('/', 'Admin\Auth\LoginController@login');
	Route::post('logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

	// Password Reset Routes...
	Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

	Route::get('home', 'Admin\HomeController@index')->name('admin.home');


	// Categorias
	Route::resource('categorias', 'Admin\CategoryController', [
		'names' => 'admin.categorias'
	]);
	Route::post('categorias/orden', 'Admin\CategoryController@sort');
	Route::post('categorias/categoriasUpload', 'Admin\CategoryController@upload')->name('admin.categories.upload.store');
	Route::post('categorias/deleteCategoriesImage', 'Admin\CategoryController@destroyImage')->name('admin.categories.upload.destroy');


	// Usuarios
	Route::resource('users', 'Admin\UserController', [
		'names' 	=> 'admin.users',
		'except'	=> 'show'
	]);

	// Marcas
	Route::resource('marcas', 'Admin\BrandController', [
		'names' 	=> 'admin.brands',
		'except'	=> 'show'
	]);

	// Attributes
	Route::resource('attributes', 'Admin\AttributeController', [
		'names' 	=> 'admin.attributes',
		'except'	=> 'show'
	]);


	// Attribute Groups
	Route::resource('groups', 'Admin\GroupController', [
		'names' 	=> 'admin.groups',
		'except'	=> 'show'
	]);

	// Features
	Route::resource('features', 'Admin\FeatureController', [
		'names' 	=> 'admin.features',
		'except'	=> 'show'
	]);

	Route::post('features/featuresUpload', 'Admin\FeatureController@upload')->name('admin.features.upload.store');
	Route::post('features/deleteFeaturesImage', 'Admin\FeatureController@destroyImage')->name('admin.features.upload.delete');


	// Productos
	Route::get('productos/importar', 'Admin\ProductController@importForm');
	Route::post('productos/importar', 'Admin\ProductController@import');
	Route::get('productos/modelo', 'Admin\ProductController@downloadImportModel');
	Route::get('productos/guia', 'Admin\ProductController@downloadImportGuide');
	Route::resource('productos', 'Admin\ProductController', [
		'names' => 'admin.productos'
	]);

	Route::post('productos/{product}/destroyManual', 'Admin\ProductController@destroyManual');


	// Productos Media
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('atributos', 'Admin\ProductController@atributos')->name('admin.productos.atributos');

		Route::post('atributos/delete', 'Admin\ProductController@deleteAtributo')->name('admin.productos.atributos.delete');

		Route::post('atributos/add', 'Admin\ProductController@addAtributos')->name('admin.productos.atributos.agregar');

		Route::get('{product}/files/create', 'Admin\ProductMediaController@create')->name('admin.productos.files.create');
		
		Route::post('{product}/files', 'Admin\ProductMediaController@store')->name('admin.productos.files.store');
		
		Route::post('{product}/files/ordenar', 'Admin\ProductMediaController@ordenar')->name('admin.productos.section.ordenar');

		Route::delete('{product}/files/{id}', 'Admin\ProductMediaController@destroy')->name('admin.productos.files.destroy');

		Route::post('{product}/deleteFilesImage', 'Admin\ProductMediaController@destroyImage')->name('admin.productos.files.destroy.images');

	});

	// Productos modulo seccion
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('{product}/section', 'Admin\ProductSectionController@store')->name('admin.productos.section.store');
		

		Route::delete('{product}/section/{id}', 'Admin\ProductSectionController@destroy')->name('admin.productos.section.destroy');
		

		Route::post('{product}/sectionUpload', 'Admin\ProductSectionController@upload')->name('admin.productos.section.upload');

		Route::post('{product}/deleteProductSectionImage', 'Admin\ProductSectionController@destroyImage')->name('admin.productos.section.destroyImage');
		
	});

	// Widgets
	Route::delete('widgets/media/{id}', 'Admin\WidgetController@deleteMedia')->name('admin.widgets.media.delete');

	Route::post('widgets/media', 'Admin\WidgetController@createMedia')->name('admin.widgets.media.store');

	Route::resource('widgets', 'Admin\WidgetController', [
		'names' => 'admin.widgets'
	]);

	Route::post('widgets/orden', 'Admin\WidgetController@ordenar')->name('admin.widgets.media.orden');

	Route::resource('slider', 'Admin\SliderController', [
		'names' => 'admin.slider'
	]);	

	Route::get('newsletter', 'NewsletterController@index')->name('admin.newsletter.index');

	// Novedades
	Route::resource('stories', 'Admin\StoryController', [
		'names' 	=> 'admin.stories',
		'except'	=> 'show'
	]);

	Route::post('stories/storiesUpload', 'Admin\StoryController@upload')->name('admin.stories.upload.store');

	// Categorias de novedades
	Route::resource('themes', 'Admin\ThemeController', [
		'names' 	=> 'admin.themes',
		'except'	=> 'show'
	]);

	// Tags
	Route::resource('tags', 'Admin\TagController', [
		'names' 	=> 'admin.tags',
		'except'	=> 'show'
	]);

	// Paginas
	Route::resource('pages', 'Admin\PageController', [
		'names' 	=> 'admin.pages',
		'except'	=> 'show'
	]);	
	Route::post('pages/orden', 'Admin\PageController@sort');
	Route::post('pages/upload', 'Admin\PageController@upload');

	//Contacto
	Route::get('contactos', 'Admin\ContactoController@index')->name('admin.contactos.index');

	//Customers
	Route::get('customers', 'Admin\CustomerController@index')->name('admin.customers.index');

	//Asuntos
	Route::resource('subjects', 'Admin\SubjectController', [
		'names' 	=> 'admin.subjects',
		'except'	=> 'show'
	]);

});


/********** FRONTEND **********/

Route::get('/', 'Front\HomeController@index')->name('home');

//Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!panel$).*$')->name('categoria');


Route::post('/newsletter', 'NewsletterController@store')->name('newsletter.store');


/*Route::get('/{category}/{subcategory?}/{product}', 'Front\ProductController@index')->name('productos');
Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto|descargas$).*$')->name('categoria');*/


// Authentication Routes...
Route::get('/login', 'Front\Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Front\Auth\LoginController@login');
Route::post('logout', 'Front\Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Front\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Front\Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Front\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Front\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Front\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Front\Auth\ResetPasswordController@reset');

// Perfil
Route::get('/perfil', 'Front\PerfilController@edit')->name('perfil.edit');
Route::put('/perfil', 'Front\PerfilController@update')->name('perfil.update');


// Contacto
Route::get('/contacto', 'Front\ContactoController@index')->name('contacto');
Route::post('/contacto', 'Front\ContactoController@store')->name('contacto.store');

// Descargas
Route::get('/descargas', 'Front\DescargasController@index')->name('descargas.index');

//Comparador
Route::post('/comparador/handle', 'Front\ComparadorController@handle');
Route::get('/comparador', 'Front\ComparadorController@index');

// Busquedas
Route::get('/busqueda', 'Front\BusquedaController@index')->name('busqueda.index');
Route::get('/autocomplete', 'Front\BusquedaController@autocomplete')->name('autocomplete');

Route::get('/{subcategory}/{product}', 'Front\ProductController@index')->name('productos');

Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto$).*$')->name('categoria');

app/Product.php
<?php

namespace Noblex;

use Illuminate\Database\Eloquent\Model;
use Noblex\Brand;
use Noblex\Attribute;
use Noblex\Category;
use Noblex\Feature;
use Noblex\ProductMedia;
use Noblex\ProductSection;
use Noblex\Relatedproduct;

class Product extends Model
{	
    protected $fillable = ["sku", "name", "url", "brand_id", "category_id", "short_description", "description", "tag", "manual","featured", "active"];

    public function productsMedia()
    {
    	return $this->hasMany(ProductMedia::class)->orderBy('position', 'asc');
    }

    public function productsGallery()
    {
        return $this->hasMany(ProductMedia::class)->where('type', 'image')->orderBy('position', 'asc');        
    }

    public function thumb()
    {
        return $this->hasOne(ProductMedia::class)->where('type', 'image_thumb');
    }

    public function featuredImg()
    {
    	return $this->hasOne(ProductMedia::class)->where('featured', 1);
    }

    public function category()
    {
    	return $this->belongsTo(Category::class);
    }

    public function features()
    {
    	return $this->belongsToMany(Feature::class)->withTimestamps();
    }

    public function relatedproducts()
    {
        return $this->belongsToMany(Product::class, 'relatedproducts', 'product_id', 'product_relationship_id')->withTimestamps();
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function sectionproducts()
    {
        return $this->hasMany(ProductSection::class);
    }

    public function attributes()
    {
        return $this->belongsToMany(Attribute::class, 'attribute_category_product', 'product_id', 'attribute_id');
    }

    public function attributesAll()
    {
        return $this->belongsToMany(Attribute::class, 'attribute_category_product', 'product_id', 'attribute_id')->withPivot('value');
    }

    public function attributesWithGroup()
    {
        $atts = $this->attributes()->whereNotNull('attributegroup_id')->orderBy('attributegroup_id', 'asc')->withPivot('value','id')->get();
        $_arr = [];
        foreach($atts as $k => $att){
            $_arr[$att->group->id]['group'] = $att->group;
            $_arr[$att->group->id]['attributes'][] = $att;
        }

        return $_arr;
    }

    public function attributesWithoutGroup()
    {
        return $this->attributes()->select()->whereNull('attributegroup_id')->orderBy('attributegroup_id', 'asc')->withPivot('value','id')->get();
    }
}

app/Http/Controllers/Front/ProductController.php
<?php

namespace Noblex\Http\Controllers\Front;

use Illuminate\Http\Request;
use Noblex\Category;
use Noblex\Http\Controllers\Front\FrontController;
use Noblex\Product;
use Noblex\ProductMedia;

class ProductController extends FrontController
{
	public function __construct()
    {
        parent::__construct();
    }
    
    public function index($subcategory, $product)
    {
        $page_id = 'producto';
        
    	$product = Product::with(['productsMedia', 'sectionproducts', 'features', 'relatedproducts'])
                            ->where('sku', $product)->firstOrFail();

        //$category = Category::where('url', $category)->first();        
        $category = Category::where('id', $product->category_id)->first();
        if ($category->root_id > 1) {
            $parentCategory = Category::where('id', $category->root_id)->first();
        }
        else {
            $parentCategory = FALSE;
        }

        if (count($product->relatedproducts)) {
            $relatedproducts = $product->relatedproducts;
            $fixedrelated = TRUE;
        }
        else {
            $relatedproducts = Product::where('category_id', $product->category_id)->where('active', 1)->where('id', '!=', $product->id)->get();
            $fixedrelated = FALSE;
        }

    	$breadcrumbs[] = ['caption' => 'Home', 'link' => ''];
        if ($parentCategory) {
            $breadcrumbs[] = ['caption' => $parentCategory->name, 'link' => $parentCategory->url];
        }
    	$breadcrumbs[] = ['caption' => $category->name, 'link' => $category->url];
        $breadcrumbs[] = ['caption' => $product->name];

    	return view('front.pages.productos', compact("breadcrumbs", "product", "relatedproducts", "page_id", "fixedrelated"));
    
    }
}

resources/views/admin/pages/products/partials/attribute.blade.php
<div class="form-group" id="attribute{{ $attribute->id }}">
    {!! Form::label("att_name", $attribute->name, ["class" => "control-label col-md-2"]) !!}
    <div class="col-md-8">
        {!! Form::text('attribute['.$attribute->id.']', $value, ["class" => "form-control attribute-input", "id" => $attribute->pivot->id, "autocomplete" => "off"]) !!}
    </div>
    <div class="col-md-2 btn-group">
        <a href="#" class="delete-attr"
        data-id="{{ $attribute->id }}">
            <i class="icon-trash"></i> Eliminar 
        </a>
    </div>
</div>

resources/views/admin/pages/products/partials/attributes.blade.php
<form id="form-atributos" method="post" action="{{ route('admin.productos.atributos') }}">
    <div class="form-body">
        <div class="form-group {{ $errors->first('features') ? 'has-error' : '' }}">
            {!! Form::label('grupos', 'Agregar atributo', ['class' => 'control-label col-md-3']) !!}
            <form id="form-add" method="post" action="{{ route('admin.productos.atributos.agregar') }}">
                <div class="col-md-6">
                    <select name="attribute_id" id="atributos" class="form-control">
                        <optgroup label=" ">
                            <option value=" "></option>
                            @foreach($attributes as $att)
                                <option id="option{{$att->id}}" value="{{ $att->id }}">{{ $att->name }}</option>
                            @endforeach
                        </optgroup>

                        @foreach($groups as $gr)
                        <optgroup label="{{ $gr['group']->name }}">
                            @foreach($gr['attributes'] as $att)
                                <option id="option{{$att->id}}" value="{{ $att->id }}">{{ $att->name }}</option>
                            @endforeach
                        </optgroup>
                        @endforeach

                    </select>
                </div>

                <div class="col-md-3">
                    <button id="add-attribute" type="button" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>

        <?php $sinagrupar = $producto->attributesWithoutGroup() ?>
        
        @if(!empty($sinagrupar) and count($sinagrupar) > 0)
        <div class="portlet box yellow">
            <div class="portlet-title">
                <div class="caption">
                    Sin agrupar
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-body" id="attributes">
                
                    @foreach($sinagrupar as $attribute)
                        @include('admin.pages.products.partials.attribute', ['attribute' => $attribute, 'value' => $attribute->pivot->value, 'id' => $attribute->id])
                    @endforeach
                </div>
            </div>
        </div>
        @endif

        @foreach($producto->attributesWithGroup() as $group)
        <div class="portlet box yellow">
            <div class="portlet-title">
                <div class="caption">
                    {{ $group['group']->name }}
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-body" id="grouped-cats">
                    
                    @foreach($group['attributes'] as $k => $attribute)
                        <div class="group" id="group{{ $attribute['group']->id }}">
                            @include('admin.pages.products.partials.attribute', ['attribute' => $attribute, 'value' => $attribute->pivot->value, 'id' => $attribute->pivot->id])
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        @endforeach
    </div>
    <div class="form-actions">
		<div class="row">
			<div class="col-md-offset-3 col-md-9">
				{!! Form::button('Guardar <i class="fa fa-angle-double-right"></i>', ['type' => 'button', 'class' => 'btn blue', 'id' => 'save-atts']) !!}
			</div>
		</div>
	</div>
</form>

@push('scripts')
<script>
$(function() {

    $("#save-atts").click(function(e){
        e.preventDefault();
        var data = [];
        $.each($(".attribute-input"), function(){
            data.push({
                id:this.id, value:this.value
            })
        });
        console.log(data);
        $.ajax({
            url: '{{ route('admin.productos.atributos') }}',
            type: 'post',
            data: { product_id:'{{ $producto->id }}', attributes:data },
            success: function(result) {
                toastr.success('Datos guardados!');
            },
            error: function(error){
                toastr.danger('Error al guardar');
            }
        });
        console.log(data);  
    });

    $(".delete-attr").click(function(e){
        e.preventDefault();
        var id = $(this).data('id');
        $.ajax({
            url: '{{ route('admin.productos.atributos.delete') }}',
            type: 'post',
            data: { 
                attribute_id: id,
                producto_id: '{{ $producto->id }}'
            },
            success: function(result) {
                toastr.success('Atributo eliminado');
                $("#attribute"+id).remove();
                $("#option"+id).attr('disabled', false);
            },
            error: function(error){
                toastr.danger('Error al eliminar');
            }
        });

        return false;
    });
    
    $('#add-attribute').click(function(){
        console.log("enviar");

        $.ajax({
            url: '{{ route('admin.productos.atributos.agregar') }}',
            type: 'post',
            data: { 
                attribute_id: $("#atributos").val(),
                producto_id: '{{ $producto->id }}'
            },
            success: function(result) {
                // console.log(result);
                // var scroll = 0;
                // if(result.group){
                //     $("#group"+result.group.id).append(result.view);
                //     scroll = $("#group"+result.group.id);
                // }else{
                //     $("#attributes").append(result.view);
                //     scroll = $("#attributes");
                    
                // }

                // $("#option"+result.attribute.id).attr('disabled', true);
                // $('html, body').animate({
                //     scrollTop: scroll.offset().top + scroll.height() - 140
                // }, 200);
                window.location = '{{ route("admin.productos.edit", $producto->id) }}' + '?tab=attributes';            },
            error: function(error){
                console.log(error);
            }
        })
    });
});
</script>
@endpush

@push('scripts')
	
@endpush

resources/views/admin/pages/products/partials/form.blade.php
	
	<div class="form-group {{ $errors->first('sku') ? 'has-error' : '' }}">
		{!! Form::label('sku', 'SKU', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::text('sku', null, ['class' => 'form-control', 'id' => 'sku', 'autocomplete' => 'off']) !!}
			{!! $errors->first('sku', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
		{!! Form::label('name', 'Nombre', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'autocomplete' => 'off']) !!}
			{!! $errors->first('name', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('url') ? 'has-error' : '' }}">
		{!! Form::label('url', 'Slug', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::text('url', null, ['class' => 'form-control', 'id' => 'url', 'autocomplete' => 'off']) !!}
			{!! $errors->first('url', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>
	
	{!! Form::hidden('brand_id', 1) !!}
	<!--
	<div class="form-group {{ $errors->first('brand_id') ? 'has-error' : '' }}">
		{!! Form::label('brand', 'Marca', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			<select name="brand_id" id="brand_id" class="form-control">
				<option value="">Seleccione una marca</option>
				
				@foreach($brands as $brand)
					<option value="{{ $brand->id }}" @if(@$producto->brand_id === $brand->id) selected @else {{ old('brand_id') != $brand->id ?: 'selected' }} @endif>{{ $brand->name }}</option>
				@endforeach

			</select>
			{!! $errors->first('brand_id', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>
	-->
	
	<div class="form-group {{ $errors->first('category_id') ? 'has-error' : '' }}" id="category">
		{!! Form::label('category', 'Categoria', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			<select name="category_id" id="category_id" class="form-control" onchange="subcategorias(this.value);">
				<option value="">Seleccione una categoría</option>
				
				@foreach($categorias as $cat)
					<option value="{{ $cat->id }}" @if(@$categoria->id == $cat->id) selected @endif>{{ $cat->name }}</option>
				@endforeach

			</select>
			{!! $errors->first('category_id', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group" id="subcategory" style="display:none">
		{!! Form::label('subcategory', 'Subcategoria', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			<select name="subcategory_id" id="subcategory_id" class="form-control">
				<option value="">Seleccione una Subcategoría</option>
			</select>
		</div>
	</div>

	<div class="form-group {{ $errors->first('short_description') ? 'has-error' : '' }}">
		{!! Form::label('short_description', 'Subtítulo', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::text('short_description', null, ['class' => 'form-control', 'id' => 'short_description', 'autocomplete' => 'off']) !!}
			{!! $errors->first('short_description', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('description') ? 'has-error' : '' }}">
		{!! Form::label('description', 'Descripción', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'description']) !!}
			{!! $errors->first('description', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('tag') ? 'has-error' : '' }}">
		{!! Form::label('tag', 'Cucarda', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-2">
			{!! Form::text('tag', null, ['class' => 'form-control', 'id' => 'name', 'maxlength' => '3']) !!}
			{!! $errors->first('tag', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('features') ? 'has-error' : '' }}">
		{!! Form::label('feature', 'Features promocional', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">

			{!! Form::select("feature_product_id[]", $features->pluck('name', 'id') , isset($producto) ? $producto->features->pluck('id') : null, ["class" => "selectpicker", "multiple" => "true" , "title"=>"Seleccione los features", "data-show-subtext"=>"true", "data-live-search"=>"true", "data-width"=>"50%"]) !!}

			{!! $errors->first('feature', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group {{ $errors->first('features') ? 'has-error' : '' }}">
		{!! Form::label('feature', 'Más features', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">

			{!! Form::select("feature_product_id[]", $features->pluck('name', 'id') , isset($producto) ? $producto->features->pluck('id') : null, ["class" => "selectpicker", "multiple" => "true" , "title"=>"Seleccione los features", "data-show-subtext"=>"true", "data-live-search"=>"true", "data-width"=>"50%"]) !!}

			{!! $errors->first('feature', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group">
		{!! Form::label('relatedproducts', 'Productos relacionados', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">

			{!! Form::select("product_relationship_id[]", $productos->pluck('name', 'id') , isset($producto) ? $producto->relatedproducts->pluck('id') : null, ["class" => "selectpicker", "multiple" => "true" , "title"=>"Seleccione los productos relacionados", "data-show-subtext"=>"true", "data-live-search"=>"true", "data-width"=>"50%"]) !!}
				
			{!! $errors->first('relatedproducts', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-group">
		{!! Form::label('active', 'Activo', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::checkbox('active', null, null, ['class' => 'make-switch', 'data-size' => 'small', 'id' => 'active']) !!}
		</div>
	</div>

	<div class="form-group">
		{!! Form::label('manual', 'Manual PDF', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::file('manual', ['class' => 'form-control', 'accept' => '.pdf']) !!}
			@isset($producto->manual)
				<div id="ver-manual">
				<small><a href='{{ url("storage/$producto->manual") }}' target='_blank'>Ver archivo cargado</a></small> | <small><a href="#" onclick="removeManual(<?php echo $producto->id; ?>);return false;">Eliminar</a></small>
				</div>
			@endisset
			<!-- <input type="file" name="manual" class="form-control" accept=".pdf"> -->
		</div>
	</div>

	<div class="form-group {{ $errors->first('featured') ? 'has-error' : '' }}">
		{!! Form::label('featured', 'Destacado', ['class' => 'control-label col-md-3']) !!}
		<div class="col-md-9">
			{!! Form::checkbox('featured', null, null, ['class' => 'make-switch', 'data-size' => 'small', 'id' => 'featured']) !!}
			{!! $errors->first('featured', '<span class="help-block"> :message </span>') !!}
		</div>
	</div>

	<div class="form-actions">
		<div class="row">
			<div class="col-md-12 text-center">
				{!! Form::button('Continuar <i class="fa fa-angle-double-right"></i>', ['type' => 'submit', 'class' => 'btn blue']) !!}
				
				<a href="{{ route('admin.productos.index') }}" type="button" class="btn default">Volver</a>

			</div>
		</div>
	</div>	