routes/web.php
<?php

/*DB::listen(function($query)
{
	echo "<pre>{{$query->sql}}</pre>";  // Para ver las consultas sql que se estan generando.
});*/


Route::group([
	'prefix'	=> 'panel'
], function() {

	// Authentication Routes...
	Route::get('/', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
	Route::post('/', 'Admin\Auth\LoginController@login');
	Route::post('logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

	// Password Reset Routes...
	Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

	Route::get('home', 'Admin\HomeController@index')->name('admin.home');


	// Categorias
	Route::resource('categorias', 'Admin\CategoryController', [
		'names' => 'admin.categorias'
	]);
	Route::post('categorias/orden', 'Admin\CategoryController@sort');
	Route::post('categorias/categoriasUpload', 'Admin\CategoryController@upload')->name('admin.categories.upload.store');
	Route::post('categorias/deleteCategoriesImage', 'Admin\CategoryController@destroyImage')->name('admin.categories.upload.destroy');


	// Usuarios
	Route::resource('users', 'Admin\UserController', [
		'names' 	=> 'admin.users',
		'except'	=> 'show'
	]);

	// Marcas
	Route::resource('marcas', 'Admin\BrandController', [
		'names' 	=> 'admin.brands',
		'except'	=> 'show'
	]);

	// Attributes
	Route::resource('attributes', 'Admin\AttributeController', [
		'names' 	=> 'admin.attributes',
		'except'	=> 'show'
	]);


	// Attribute Groups
	Route::resource('groups', 'Admin\GroupController', [
		'names' 	=> 'admin.groups',
		'except'	=> 'show'
	]);

	// Features
	Route::resource('features', 'Admin\FeatureController', [
		'names' 	=> 'admin.features',
		'except'	=> 'show'
	]);

	Route::post('features/featuresUpload', 'Admin\FeatureController@upload')->name('admin.features.upload.store');
	Route::post('features/deleteFeaturesImage', 'Admin\FeatureController@destroyImage')->name('admin.features.upload.delete');


	// Productos
	Route::get('productos/importar', 'Admin\ProductController@importForm');
	Route::post('productos/importar', 'Admin\ProductController@import');
	Route::get('productos/modelo', 'Admin\ProductController@downloadImportModel');
	Route::get('productos/guia', 'Admin\ProductController@downloadImportGuide');
	Route::resource('productos', 'Admin\ProductController', [
		'names' => 'admin.productos'
	]);

	Route::post('productos/{product}/destroyManual', 'Admin\ProductController@destroyManual');


	// Productos Media
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('atributos', 'Admin\ProductController@atributos')->name('admin.productos.atributos');

		Route::post('atributos/delete', 'Admin\ProductController@deleteAtributo')->name('admin.productos.atributos.delete');

		Route::post('atributos/add', 'Admin\ProductController@addAtributos')->name('admin.productos.atributos.agregar');

		Route::get('{product}/files/create', 'Admin\ProductMediaController@create')->name('admin.productos.files.create');
		
		Route::post('{product}/files', 'Admin\ProductMediaController@store')->name('admin.productos.files.store');
		
		Route::post('{product}/files/ordenar', 'Admin\ProductMediaController@ordenar')->name('admin.productos.section.ordenar');

		Route::delete('{product}/files/{id}', 'Admin\ProductMediaController@destroy')->name('admin.productos.files.destroy');

		Route::post('{product}/deleteFilesImage', 'Admin\ProductMediaController@destroyImage')->name('admin.productos.files.destroy.images');

	});

	// Productos modulo seccion
	Route::group([
		'prefix' => 'productos'
	], function() { 

		Route::post('{product}/section', 'Admin\ProductSectionController@store')->name('admin.productos.section.store');
		

		Route::delete('{product}/section/{id}', 'Admin\ProductSectionController@destroy')->name('admin.productos.section.destroy');
		

		Route::post('{product}/sectionUpload', 'Admin\ProductSectionController@upload')->name('admin.productos.section.upload');

		Route::post('{product}/deleteProductSectionImage', 'Admin\ProductSectionController@destroyImage')->name('admin.productos.section.destroyImage');
		
	});

	// Widgets
	Route::delete('widgets/media/{id}', 'Admin\WidgetController@deleteMedia')->name('admin.widgets.media.delete');

	Route::post('widgets/media', 'Admin\WidgetController@createMedia')->name('admin.widgets.media.store');

	Route::resource('widgets', 'Admin\WidgetController', [
		'names' => 'admin.widgets'
	]);

	Route::post('widgets/orden', 'Admin\WidgetController@ordenar')->name('admin.widgets.media.orden');

	Route::resource('slider', 'Admin\SliderController', [
		'names' => 'admin.slider'
	]);	

	Route::get('newsletter', 'NewsletterController@index')->name('admin.newsletter.index');

	// Novedades
	Route::resource('stories', 'Admin\StoryController', [
		'names' 	=> 'admin.stories',
		'except'	=> 'show'
	]);

	Route::post('stories/storiesUpload', 'Admin\StoryController@upload')->name('admin.stories.upload.store');

	// Categorias de novedades
	Route::resource('themes', 'Admin\ThemeController', [
		'names' 	=> 'admin.themes',
		'except'	=> 'show'
	]);

	// Tags
	Route::resource('tags', 'Admin\TagController', [
		'names' 	=> 'admin.tags',
		'except'	=> 'show'
	]);

	// Paginas
	Route::resource('pages', 'Admin\PageController', [
		'names' 	=> 'admin.pages',
		'except'	=> 'show'
	]);	
	Route::post('pages/orden', 'Admin\PageController@sort');
	Route::post('pages/upload', 'Admin\PageController@upload');

	//Contacto
	Route::get('contactos', 'Admin\ContactoController@index')->name('admin.contactos.index');

	//Customers
	Route::get('customers', 'Admin\CustomerController@index')->name('admin.customers.index');

	//Asuntos
	Route::resource('subjects', 'Admin\SubjectController', [
		'names' 	=> 'admin.subjects',
		'except'	=> 'show'
	]);

});


/********** FRONTEND **********/

Route::get('/', 'Front\HomeController@index')->name('home');

//Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!panel$).*$')->name('categoria');


Route::post('/newsletter', 'NewsletterController@store')->name('newsletter.store');


/*Route::get('/{category}/{subcategory?}/{product}', 'Front\ProductController@index')->name('productos');
Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto|descargas$).*$')->name('categoria');*/


// Authentication Routes...
Route::get('/login', 'Front\Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Front\Auth\LoginController@login');
Route::post('logout', 'Front\Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Front\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Front\Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Front\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Front\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Front\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Front\Auth\ResetPasswordController@reset');

// Perfil
Route::get('/perfil', 'Front\PerfilController@edit')->name('perfil.edit');
Route::put('/perfil', 'Front\PerfilController@update')->name('perfil.update');


// Contacto
Route::get('/contacto', 'Front\ContactoController@index')->name('contacto');
Route::post('/contacto', 'Front\ContactoController@store')->name('contacto.store');

// Descargas
Route::get('/descargas', 'Front\DescargasController@index')->name('descargas.index');

//Comparador
Route::post('/comparador/handle', 'Front\ComparadorController@handle');
Route::get('/comparador', 'Front\ComparadorController@index');

// Busquedas
Route::get('/busqueda', 'Front\BusquedaController@index')->name('busqueda.index');
Route::get('/autocomplete', 'Front\BusquedaController@autocomplete')->name('autocomplete');

Route::get('/{subcategory}/{product}', 'Front\ProductController@index')->name('productos');

Route::get('/{slug}', 'Front\CategoryController@index')->where('slug', '^(?!login|register|contacto$).*$')->name('categoria');

resources/views/admin/includes/bar.blade.php
<div class="page-bar">
    @section('admin.includes.breadcrumbs')

    @show
</div>

resources/views/admin/includes/breadcrumbs.blade.php
@if (count($breadcrumbs))

    <ul class="page-breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li>
                	<a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a>
                	<i class="fa fa-circle"></i>
                </li>
            @else
                <li>{{ $breadcrumb->title }}</li>
            @endif

        @endforeach
    </ul>

@endif

resources/views/admin/includes/footer.blade.php
<div class="page-footer">
        
</div>

</div>
<!-- END PAGE-WRAPPER -->

<script>
	var baseUrl = "{{ url('panel/') }}";
	var storageUrl = "{{ url('storage/') }}";
	// $.ajaxSetup({
	// 	headers: {
	// 		'X-CSRF-TOKEN': '{{ csrf_token() }}'
	// 	}
	// });
</script>
 
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('admin/assets/global/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('admin/assets/global/plugins/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('admin/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}"></script>


@stack('scripts')

</body>
</html>

resources/views/admin/includes/head.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{{ config('app.name') }}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" />
    <link href="{{ asset('admin/assets/global/plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('admin/assets/global/plugins/simple-line-icons/simple-line-icons.min.css') }}" rel="stylesheet" />

    <link href="{{ asset('admin/assets/global/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset('admin/assets/global/plugins/datatables/datatables.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('admin/assets/global/css/plugins.min.css') }}" rel="stylesheet" />

    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    @stack('styles')
    
</head>

resources/views/admin/includes/header.blade.php
<div class="page-header navbar navbar-fixed-top">

    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ route('admin.home') }}">
                <img src="{{ asset('assets/imgs/iconos/noblex_blanco.png') }}" alt="logo" class="logo-default img-responsive" />
            </a>

            <div class="menu-toggler sidebar-toggler hidden">
                <span></span>
            </div>

        </div>
        <!-- END LOGO -->

        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->

        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                @guest
                    <li><a class="nav-link" href="{{ route('admin.login') }}">{{ __('Login') }}</a></li>
                @else
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="username username-hide-on-mobile"> {{ ucwords(Auth::user()->name) }} </span>
                            <i class="fa fa-angle-down"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-default">
                            <!--
                            <li>
                                <a href="#">
                                    <i class="icon-user"></i> Perfil 
                                </a>
                            </li>
                            <li class="divider"> </li>
                            -->
                            <li>
                                <a class="dropdown-item" href="{{ route('admin.logout') }}"
                                   onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                    <i class="icon-key"></i> Salir
                                </a>

                                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </li>
                @endguest
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->

</div>

<!-- BEGIN HEADER & CONTENT DIVIDER -->
<div class="clearfix"></div>
<!-- END HEADER & CONTENT DIVIDER -->

resources/views/admin/includes/menu.blade.php
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->

    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->

        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">


            <li class="nav-item start {{ activeMenu('panel/home') }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>
            </li>

            @if (\Auth::user()->admin)
            <li class="nav-item start {{ activeMenu('panel/marcas*') }}">
                <a href="{{ route('admin.brands.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Marcas</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/users*') }}">
                <a href="{{ route('admin.users.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Usuarios</span>
                </a>
            </li>
            @endif

            <li class="nav-item start {{ activeMenu('panel/slider*') ? activeMenu('panel/slider*') : (activeMenu('panel/widgets*') ? activeMenu('panel/widgets*') : '') }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Pagina inicial</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start {{ activeMenu('panel/slider*') }}">
                        <a href="{{ route('admin.slider.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Slider</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/widgets*') }}">
                        <a href="{{ route('admin.widgets.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Widgets</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item start {{ activeMenu('panel/features*') ? activeMenu('panel/features*') : (activeMenu('panel/attribute*') ? activeMenu('panel/attribute*') : (activeMenu('panel/groups*') ? activeMenu('panel/groups*') : activeMenu('panel/subjects*')))  }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Configuracion</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start {{ activeMenu('panel/features*') }}">
                        <a href="{{ route('admin.features.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Features</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/attribute*') }}">
                        <a href="{{ route('admin.attributes.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Atributos</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/groups*') }}">
                        <a href="{{ route('admin.groups.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Grupos de Atributos</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/subjects*') }}">
                        <a href="{{ route('admin.subjects.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Asuntos</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item start {{ activeMenu('panel/categorias*') }}">
                <a href="{{ route('admin.categorias.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Categorias</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/productos*') }}">
                <a href="{{ route('admin.productos.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Productos</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/newsletter*') }}">
                <a href="{{ route('admin.newsletter.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Newsletter</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/stories') ? activeMenu('panel/stories') : (activeMenu('panel/tags') ? activeMenu('panel/tags') : (activeMenu('panel/themes*') ? activeMenu('panel/themes*') : '')) }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Novedades</span>
                    <span class="selected"></span>
                    <span class="arrow open"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start {{ activeMenu('panel/stories*') }}">
                        <a href="{{ route('admin.stories.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Novedades</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/tags*') }}">
                        <a href="{{ route('admin.tags.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Etiquetas</span>
                        </a>
                    </li>
                    <li class="nav-item start {{ activeMenu('panel/themes*') }}">
                        <a href="{{ route('admin.themes.index') }}" class="nav-link nav-toggle">
                            <i class="icon-list"></i>
                            <span class="title">Categorías</span>
                        </a>
                    </li>
                </ul>
            </li>            
            <li class="nav-item start {{ activeMenu('panel/pages*') }}">
                <a href="{{ route('admin.pages.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Páginas de Contenido</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/contactos*') }}">
                <a href="{{ route('admin.contactos.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Contactos</span>
                </a>
            </li>
            <li class="nav-item start {{ activeMenu('panel/customers*') }}">
                <a href="{{ route('admin.customers.index') }}" class="nav-link nav-toggle">
                    <i class="icon-list"></i>
                    <span class="title">Clientes</span>
                </a>
            </li>            
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>